#!/bin/bash
# auto-checkpoint.sh
# Event: Stop (async: true)
#
# At session end, writes a minimal git-status savepoint to .claude/checkpoints/.
# Only runs if source files were modified — skips Q&A-only sessions.
#
# Output: .claude/checkpoints/YYYY-MM-DD-HH-MM-auto.md
# Contains: modified file list, git status, recent commits
#
# Note: This is a structural checkpoint based on git state.
# For an AI-analyzed checkpoint (decisions, blockers, next steps), use /checkpoint instead.

INPUT=$(cat)

# Require git
command -v git &>/dev/null || exit 0

# Check for modified source or config files (not untracked)
MODIFIED=$(git status --porcelain 2>/dev/null \
  | grep -v "^??" \
  | awk '{print $2}' \
  | grep -v "^\.claude/" \
  | grep -E "\.(py|js|ts|jsx|tsx|php|go|rs|rb|java|md|json|yml|yaml)$")

# No relevant changes — skip
[ -z "$MODIFIED" ] && exit 0

# Create checkpoint directory
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
CHECKPOINT_DIR="$PROJECT_DIR/.claude/checkpoints"
mkdir -p "$CHECKPOINT_DIR" 2>/dev/null || exit 0

TIMESTAMP=$(date +"%Y-%m-%d-%H-%M")
CHECKPOINT_FILE="$CHECKPOINT_DIR/${TIMESTAMP}-auto.md"

{
  echo "# Auto-Checkpoint — ${TIMESTAMP}"
  echo ""
  echo "> Generated by the auto-checkpoint hook. For full context analysis, run /checkpoint."
  echo ""
  echo "## Modified Files"
  echo ""
  echo "$MODIFIED" | while read -r f; do echo "- \`$f\`"; done
  echo ""
  echo "## Git Status"
  echo ""
  echo "\`\`\`"
  git status --short 2>/dev/null
  echo "\`\`\`"
  echo ""
  echo "## Recent Commits"
  echo ""
  echo "\`\`\`"
  git log --oneline -5 2>/dev/null
  echo "\`\`\`"
} > "$CHECKPOINT_FILE"

echo "Checkpoint saved: $CHECKPOINT_FILE"
exit 0
